# Generated by Django 3.2.5 on 2024-12-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_bytes_app', '0002_auto_20241126_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservation_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of reservations for this event'),
        ),
    ]
