# Generated by Django 3.2.5 on 2024-12-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_bytes_app', '0003_event_reservation_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allergies',
            field=models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Soy', 'Soy'), ('Nuts', 'Nuts'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Eggs', 'Eggs'), ('Wheat', 'Wheat'), ('Sesame', 'Sesame')], help_text='Select common allergens to be aware of.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='food_types',
            field=models.CharField(blank=True, choices=[('Italian', 'Italian'), ('Mediterranean', 'Mediterranean'), ('Salad', 'Salad'), ('American', 'American'), ('BBQ', 'BBQ'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Mexican', 'Mexican'), ('Spanish', 'Spanish'), ('Indian', 'Indian'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese'), ('Sushi', 'Sushi'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], help_text='Select the type of food available.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='buid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
