# Generated by Django 3.2.5 on 2024-12-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_bytes_app', '0004_auto_20241208_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
