# Generated by Django 4.2.17 on 2024-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_bytes_app', '0005_auto_20241208_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event description (optional)', null=True),
        ),
    ]
