# Generated by Django 4.2.17 on 2024-12-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_bytes_app', '0006_remove_event_location_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
        ),
    ]
